// <auto-generated />
using System;
using CourrierDocker_MBDS_31.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourrierDocker_MBDS_31.Migrations
{
    [DbContext(typeof(CourrierDocker_MBDS_31Context))]
    partial class CourrierDocker_MBDS_31ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.account.MyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDepartement")
                        .HasColumnType("int");

                    b.Property<int>("IdPoste")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserDepartementId")
                        .HasColumnType("int");

                    b.Property<int?>("UserPostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserDepartementId");

                    b.HasIndex("UserPostId");

                    b.ToTable("MyUser");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.courrier.Commentaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCommentateur")
                        .HasColumnType("int");

                    b.Property<int>("IdCourrier")
                        .HasColumnType("int");

                    b.Property<int?>("commentateurId")
                        .HasColumnType("int");

                    b.Property<string>("contenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("courrierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dateCommentaire")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("commentateurId");

                    b.HasIndex("courrierId");

                    b.ToTable("Commentaire");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.courrier.Courrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreateurId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpediteurId")
                        .HasColumnType("int");

                    b.Property<int>("IdCreateur")
                        .HasColumnType("int");

                    b.Property<int>("IdExpediteur")
                        .HasColumnType("int");

                    b.Property<int>("IdPriorite")
                        .HasColumnType("int");

                    b.Property<string>("contenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("objet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("prioriteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateurId");

                    b.HasIndex("ExpediteurId");

                    b.HasIndex("prioriteId");

                    b.ToTable("Courrier");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.courrier.Destinataire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCourrier")
                        .HasColumnType("int");

                    b.Property<int>("IdDepartementDestinataire")
                        .HasColumnType("int");

                    b.Property<int?>("courrierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateReceptionDirecteur")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateReceptionSecretaire")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateTransmission")
                        .HasColumnType("datetime2");

                    b.Property<int?>("departementDestinataireId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("courrierId");

                    b.HasIndex("departementDestinataireId");

                    b.ToTable("Destinataire");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.courrier.FichierJoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCourrier")
                        .HasColumnType("int");

                    b.Property<int?>("courrierId")
                        .HasColumnType("int");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("courrierId");

                    b.ToTable("FichierJoint");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.courrier.Priorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Val")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Priorite");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.structure.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Val")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departement");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.structure.Poste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Val")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Poste");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.account.MyUser", b =>
                {
                    b.HasOne("CourrierDocker_MBDS_31.modeles.structure.Departement", "UserDepartement")
                        .WithMany()
                        .HasForeignKey("UserDepartementId");

                    b.HasOne("CourrierDocker_MBDS_31.modeles.structure.Poste", "UserPost")
                        .WithMany()
                        .HasForeignKey("UserPostId");

                    b.Navigation("UserDepartement");

                    b.Navigation("UserPost");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.courrier.Commentaire", b =>
                {
                    b.HasOne("CourrierDocker_MBDS_31.modeles.account.MyUser", "commentateur")
                        .WithMany()
                        .HasForeignKey("commentateurId");

                    b.HasOne("CourrierDocker_MBDS_31.modeles.courrier.Courrier", "courrier")
                        .WithMany()
                        .HasForeignKey("courrierId");

                    b.Navigation("commentateur");

                    b.Navigation("courrier");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.courrier.Courrier", b =>
                {
                    b.HasOne("CourrierDocker_MBDS_31.modeles.account.MyUser", "Createur")
                        .WithMany()
                        .HasForeignKey("CreateurId");

                    b.HasOne("CourrierDocker_MBDS_31.modeles.account.MyUser", "Expediteur")
                        .WithMany()
                        .HasForeignKey("ExpediteurId");

                    b.HasOne("CourrierDocker_MBDS_31.modeles.courrier.Priorite", "priorite")
                        .WithMany()
                        .HasForeignKey("prioriteId");

                    b.Navigation("Createur");

                    b.Navigation("Expediteur");

                    b.Navigation("priorite");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.courrier.Destinataire", b =>
                {
                    b.HasOne("CourrierDocker_MBDS_31.modeles.courrier.Courrier", "courrier")
                        .WithMany()
                        .HasForeignKey("courrierId");

                    b.HasOne("CourrierDocker_MBDS_31.modeles.structure.Departement", "departementDestinataire")
                        .WithMany()
                        .HasForeignKey("departementDestinataireId");

                    b.Navigation("courrier");

                    b.Navigation("departementDestinataire");
                });

            modelBuilder.Entity("CourrierDocker_MBDS_31.modeles.courrier.FichierJoint", b =>
                {
                    b.HasOne("CourrierDocker_MBDS_31.modeles.courrier.Courrier", "courrier")
                        .WithMany()
                        .HasForeignKey("courrierId");

                    b.Navigation("courrier");
                });
#pragma warning restore 612, 618
        }
    }
}
